test: Add rnapolis config-annotator test for 1EHZ output

diff --git a/.github/workflows/build-and-push-rnapolis.yml b/.github/workflows/build-and-push-rnapolis.yml
--- a/.github/workflows/build-and-push-rnapolis.yml
+++ b/.github/workflows/build-and-push-rnapolis.yml
@@ -98,6 +98,20 @@ jobs:
               exit 1
             fi
           done
+
+          cli2rest-bio --api-url http://localhost:$HOST_PORT --output-metadata metadata.json src/cli2rest_bio/configs/rnapolis/config-annotator.yaml 1ehz.pdb
+          if [ "$(jq -r .status metadata.json)" != "COMPLETED" ]; then
+            echo "Test failed: Job status is not COMPLETED"
+            cat metadata.json
+            exit 1
+          fi
+
+          if [ ! -f "rnapolis-1ehz-output.json" ]; then
+            echo "Test failed: Output file rnapolis-1ehz-output.json is missing."
+            ls -l
+            exit 1
+          fi
+
           echo "Test passed: All output files created."
 
           docker stop cli2rest-rnapolis-test
